---
stages:
- name: build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: output
    build_type: shell
    script: "#!/bin/bash\n\n#Install meteor if its not installed\nhash meteor 2>/dev/null\
      \ || curl https://install.meteor.com | /bin/sh\n\n#Add ~/.meteor to the path\
      \ to workaround non-sudo installation issue\nhash meteor 2>/dev/null || PATH=$PATH:$HOME/.meteor\n\
      \n# remove default accounts pkgs\nmeteor remove accounts-ui accounts-password\n\
      \n# get accounts-couchdb package\ngit clone https://github.com/mariobriggs/meteor-accounts-couchdb.git\n\
      mv ./meteor-accounts-couchdb/packages/ .\nrm -rf meteor-accounts-couchdb/\n\
      #set package_dirs to pickup accounts-couchdb package\nexport PACKAGE_DIRS=./packages/\n\
      \n# add local accounts packages & cloudant:couchdb\nmeteor add accounts-password-couchdb\
      \ accounts-password accounts-ui cloudant:couchdb\n\n# install demeteorizer npm\
      \ module\nnpm install -g demeteorizer@2.3.1\n\n# run demeteorizer\ndemeteorizer\
      \ -o output\n\n# generate a rand word to use in route in manifest file\nRAND=$(date\
      \ +%s | sha256sum | base64 | head -c 6)\n\n#create manifest file\necho applications:\
      \ >> output/manifest.yml\necho - services: >> output/manifest.yml\necho '  -\
      \ cloudant-meteor' >> output/manifest.yml\necho '  name: mymeteor' >> output/manifest.yml\n\
      echo \"  host: mymeteor-${RAND}\" >> output/manifest.yml\necho '  memory: 512M'\
      \ >> output/manifest.yml\n\necho '  env:' >> output/manifest.yml\necho \"  \
      \  ROOT_URL: https://mymeteor-${RAND}.mybluemix.net\" >> output/manifest.yml\n\
      echo '    MONGO_URL: nope' >> output/manifest.yml\necho >> output/manifest.yml\n\
      \ncat output/manifest.yml "
- name: deploy
  inputs:
  - type: job
    stage: build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: https://api.ng.bluemix.net
      organization: mario.briggs@in.ibm.com
      space: dev
      application: articleDeploy
    script: "#!/bin/bash\ncf create-service cloudantNoSQLDB Shared cloudant-meteor\
      \ \ncf push \"${CF_APP}\"\n"
